### ISSUE TITLE
(Request) Support for Desitorrents

### ISSUE THREAD

**Issue by High-rider** [L4GSP1KE/Upload-Assistant#266] opened 2023-10-13 05:57 UTC
UNIT3D based tracker, won't be much issue I think

Please.

**Comment by L4GSP1KE** [comment] 2023-10-13 20:22
Dupe of https://github.com/L4GSP1KE/Upload-Assistant/issues/136

**Closed by L4GSP1KE** 2023-10-13 20:22 UTC

**Comment by MasalaTalk** [comment] 2023-10-18 20:25
Yes, please add support for DT.
